name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build project
        run: mvn clean package

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          echo "VdbtzGcHKiJS!8V" | docker login -u "jamieossip@yahoo.com" --password-stdin

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Push Docker image
        run: |
          docker tag my-app:latest jamieossip/my-app:latest
          docker push jamieossip/my-app:latest
